// languages that have translation files in `public/locales`
export const i18nLanguages = [
  'da',
  'en',
  'en-GB',
  'en-US',
  'es',
  'fr',
  'fr-FR',
  'it',
  'ja',
  'ms',
  'nb',
  'ro',
  'ru',
  'sv',
  'yue',
  'zh',
  'zh-CN',
  'zh-HK',
  'zh-TW',
] as const;

// languages that are selectable on the web page
export const selectableLanguages = [
  'da',
  'en-GB',
  'en-US',
  'es',
  'fr-FR',
  'it',
  'ja',
  'ms',
  'nb',
  'ro',
  'ru',
  'sv',
  'yue',
  'zh-CN',
  'zh-TW',
] as const;

export const languageCodeToName = {
  'da': 'Dansk',
  'en': 'English',
  'en-GB': 'English (UK)',
  'en-US': 'English (US)',
  'es': 'Español',
  'fr': 'Français',
  'fr-FR': 'Français',
  'it': 'Italiano',
  'ja': '日本語',
  'ms': 'Bahasa Melayu',
  'nb': 'Norsk bokmål',
  'ro': 'Română',
  'ru': 'Русский',
  'sv': 'Svenska',
  'yue': '廣東話',
  'zh': '中文',
  'zh-CN': '中文（简体）',
  'zh-HK': '廣東話',
  'zh-TW': '中文（台灣）',
};
